name: freemannlifesteal
version: 1.0
author: Freemann
main: fr.freemann.Main
commands:   
  giveheart:
    description: Give yourself an hearth
  lshelp:
    description : get some help i guess
  withdraw:
    description: get an heart item